  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  jobs:
    build:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Set up Docker Build
          uses: docker/setup-buildx-action@v1
          with:
            context: .
            file: ./Dockerfile


