  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  jobs:
    build:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.DOCKER_ACCES }}
        - name: Set up Docker Build  image and push this to dockerhub
          uses: docker/setup-buildx-action@v1
          with:
            context: .
            file: ./Dockerfile
            builder: ${{ steps.buildx.outputs.name }}
            push: true
            tags: ${{ secrets.USERNAME }}/fast_api_project:latest



