  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  jobs:
    build:
      runs-on: ubuntu-20.04
      environment: dev
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name : Check secrets
          run: |
            echo "username="
            echo ${{ secrets.USERNAME }}
        - name: Login to Docker Hub
          env:
            username: ${{ secrets.USERNAME }}
            password: ${{ secrets.DOCKER_ACCES }}
          run: |
            docker login -u $username -p $password
        - name: Build docker image
          run: | 
            docker build -t app:latest .
        - name: Tag image to docker hub repo
          run: |
            docker tag app ${{ secrets.USERNAME }}/fast_api_project
        - name: Push docker image to docker hub
          run: |
            docker push ${{ secrets.USERNAME }}/fast_api_project



